# Generated by Django 5.2 on 2025-07-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fofoca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('bairro', models.CharField(choices=[('CENTRO', 'Centro'), ('AQUARIUS', 'Jardim Aquarius'), ('SATELITE', 'Jardim Satélite'), ('URBANOVA', 'Urbanova'), ('VILA_EMA', 'Vila Ema'), ('BOSQUE', 'Bosque dos Eucaliptos'), ('ESPLANADA', 'Jardim Esplanada'), ('PARQUE_INDUSTRIAL', 'Parque Industrial'), ('ALTOS', 'Altos de Santana'), ('DOM_PEDRO', 'Dom Pedro I'), ('VISTA_VERDE', 'Vista Verde'), ('JD_AUGUSTO', 'Jardim São José'), ('OUTROS', 'Outros')], max_length=50)),
                ('categoria', models.CharField(choices=[('comercio', 'Comércio'), ('relacionamento', 'Relacionamento'), ('obra', 'Obra'), ('bizarro', 'Bizarro'), ('outro', 'Outro')], max_length=20)),
                ('votos_confirmo', models.PositiveIntegerField(default=0)),
                ('votos_mentira', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
